[supervisord]
nodaemon = true
logfile=/app/var/log/supervisord.log
pidfile=/app/var/log/supervisord.pid
logfile_backups=2

[program:php]
command=/usr/local/sbin/php-fpm -F
priority=1
autostart=true
autorestart=true
stdout_events_enabled=true
stderr_events_enabled=true
numprocs=1

[program:cache-clear]
command=php /app/bin/console cache:clear
startsecs = 0
priority=3
autostart=true
autorestart=false
stdout_events_enabled=true
stderr_events_enabled=true
stderr_logfile=/app/var/log/cache-clear.err.log
numprocs=1

[program:migrations]
command=php /app/bin/console doctrine:migrations:migrate --no-interaction
startsecs=0
priority=4
autostart=true
autorestart=false
stdout_events_enabled=true
stderr_events_enabled=true
stderr_logfile=/app/var/log/migrations.err.log
numprocs=1

[program:composer]
command=php composer install
startsecs=0
priority=5
autostart=true
autorestart=false
stdout_events_enabled=true
stderr_events_enabled=true
stderr_logfile=/app/var/log/composer.err.log
numprocs=1

[program:messenger_async_stop_running_jobs]
command=php /app/bin/console messenger:stop-workers
startsecs = 0
priority=6
autostart=true
autorestart=false
stdout_events_enabled=true
stderr_events_enabled=true
stderr_logfile=/app/var/log/messenger-async-stop.err.log
numprocs=1

[program:messenger_async]
numprocs=1
command=php /app/bin/console messenger:consume async --memory-limit=0 -vv
startsecs = 0
priority=7
stderr_logfile=/app/var/log/messenger-async.err.log
stdout_logfile_maxbytes=500MB
autostart=true
autorestart=true
startretries=5
stdout_events_enabled=true
stderr_events_enabled=true
process_name=%(program_name)s_%(process_num)02d
